<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Pooja-17125" failures="1" tests="8" name="PriorityDemo.TestNGRetryFailedDemo" time="0.046" errors="0" timestamp="04 Apr 2020 07:54:48 GMT" skipped="5">
  <testcase classname="PriorityDemo.TestNGRetryFailedDemo" name="test2" time="0.001"/>
  <testcase classname="PriorityDemo.TestNGRetryFailedDemo" name="test3" time="0.004">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertTrue(Assert.java:52)
at PriorityDemo.TestNGRetryFailedDemo.test3(TestNGRetryFailedDemo.java:35)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase classname="PriorityDemo.TestNGRetryFailedDemo" name="test3" time="0.003">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase classname="PriorityDemo.TestNGRetryFailedDemo" name="test3" time="0.003">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase classname="PriorityDemo.TestNGRetryFailedDemo" name="test1" time="0.026"/>
  <testcase classname="PriorityDemo.TestNGRetryFailedDemo" name="test3" time="0.004">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase classname="PriorityDemo.TestNGRetryFailedDemo" name="test3" time="0.002">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase classname="PriorityDemo.TestNGRetryFailedDemo" name="test3" time="0.003">
    <skipped/>
  </testcase> <!-- test3 -->
</testsuite> <!-- PriorityDemo.TestNGRetryFailedDemo -->
